[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 775 storage bootstrap/cache"
]

[phases.build]
cmds = []

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"